### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by cheetahbyte** [DreamTexX/securite#1]
I think that this project should be pronounced *[sekyʀite]*.

**Comment by DreamTexX** [comment]
More like /sekyʀit/

**Comment by cheetahbyte** [comment]
No, because c'est un mot francaise.

**Comment by DreamTexX** [comment]
It is based on a french word, but it is not this exact french word

**Comment by cheetahbyte** [comment]
Du kannst nicht einfach die Accents wegmachen und sagen, das Wort wäre französisch.
Es gibt das Wort in keiner anderen Sprache
